In [1]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())


2.6.0+cu124
True


### Creating a Tensor

In [2]:
# using empty
a =torch.empty(2,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [3]:
# check type
type(a)

torch.Tensor

In [4]:
b = torch.zeros(2,3)
b

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
c = torch.ones(2,3)
c

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [6]:
d = torch.rand(2,3)
d

tensor([[0.2685, 0.8947, 0.6982],
        [0.3155, 0.9213, 0.8212]])

In [7]:
# manual seed
torch.manual_seed(42)
e = torch.rand(2,3)
e

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [8]:
# using tensor
f = torch.tensor([[1,2,3],[4,5,6]])
f

tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
# using arange
g = torch.arange(0,100,10)
g

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [10]:
#using linspace
h = torch.linspace(0,1,10)
h

tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])

In [11]:
# using identity
i = torch.eye(3)
i

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

### Tensor shape

In [12]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
x.shape

torch.Size([2, 3])

In [16]:
torch.empty_like(x) # place where these tensor values are stored

tensor([[    133523323309456,     133523323309456,                   0],
        [                  0,                   0, 7310593858020254331]])

In [17]:
torch.empty_like(x).shape

torch.Size([2, 3])

In [18]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [19]:
torch.ones_like(x)


tensor([[1, 1, 1],
        [1, 1, 1]])

### Tensor data types

In [20]:
x.dtype

torch.int64

In [21]:
# assign the data type
y = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32)
y

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### Mathematical Operations

In [22]:
x = torch.rand(2,2)
x

tensor([[0.2566, 0.7936],
        [0.9408, 0.1332]])

In [23]:
x=x+2
x

tensor([[2.2566, 2.7936],
        [2.9408, 2.1332]])

In [24]:
x=x-1
x

tensor([[1.2566, 1.7936],
        [1.9408, 1.1332]])

In [25]:
x= x*3
x

tensor([[3.7697, 5.3809],
        [5.8223, 3.3996]])

In [26]:
x = x/1.3
x

tensor([[2.8998, 4.1392],
        [4.4787, 2.6150]])

In [27]:
x = x//2
x

tensor([[1., 2.],
        [2., 1.]])

In [36]:
x = x**3
x

tensor([[  1., 512.],
        [512.,   1.]])

In [37]:
torch.abs(x)

tensor([[  1., 512.],
        [512.,   1.]])

In [38]:
torch.neg(x)

tensor([[  -1., -512.],
        [-512.,   -1.]])

In [39]:
torch.round(x)

tensor([[  1., 512.],
        [512.,   1.]])

In [40]:
torch.ceil(x)

tensor([[  1., 512.],
        [512.,   1.]])

In [41]:
torch.floor(x)

tensor([[  1., 512.],
        [512.,   1.]])

In [43]:
d

tensor([[0.2685, 0.8947, 0.6982],
        [0.3155, 0.9213, 0.8212]])

In [46]:
# clamp
torch.clamp(d, min =0.03 , max=0.9)

tensor([[0.2685, 0.8947, 0.6982],
        [0.3155, 0.9000, 0.8212]])

In [47]:
x.sum()

tensor(1026.)

In [48]:
# sum along column
x.sum(axis=0)

tensor([513., 513.])

In [49]:
x.sum(axis=1)

tensor([513., 513.])

In [50]:
x.mean()

tensor(256.5000)

In [51]:
torch.argmax(x)

tensor(1)

In [52]:
torch.argmin(x)# return index

tensor(0)

In [53]:
torch.median(x)

tensor(1.)

In [54]:
torch.prod(x)

tensor(262144.)

In [55]:
torch.std(x)

tensor(295.0260)

In [56]:
torch.matmul(x,y) # matrix multiplication

tensor([[2049., 2562., 3075.],
        [ 516., 1029., 1542.]])

In [57]:
# dot product
torch.dot(x, y)

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [58]:
# tanspose
torch.t(x)

tensor([[  1., 512.],
        [512.,   1.]])

In [59]:
torch.det(x)

tensor(-262143.)

In [60]:
# sigmoid
torch.sigmoid(x)

tensor([[0.7311, 1.0000],
        [1.0000, 0.7311]])

In [61]:
torch.relu(x)

tensor([[  1., 512.],
        [512.,   1.]])

In [62]:
m = torch.rand(2,3)
n = torch.rand(2,3)

In [63]:
m + n # creating a new tensor all together

tensor([[1.8200, 1.1675, 1.1360],
        [1.1952, 1.0107, 0.8708]])

In [64]:
torch.relu_(m)

tensor([[0.9346, 0.5936, 0.8694],
        [0.5677, 0.7411, 0.4294]])

In [65]:
m # now existing tensor is changed
#hence no extra space is used


tensor([[0.9346, 0.5936, 0.8694],
        [0.5677, 0.7411, 0.4294]])

In [66]:
# creating a new tensor on GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

cuda


In [74]:
device = torch.device("cuda")

In [75]:
#creating a tensor on gpu
torch.rand((2,3), device=device)

tensor([[0.9877, 0.1289, 0.5621],
        [0.5221, 0.7445, 0.5955]], device='cuda:0')

In [76]:
# moving a existing tensor on to the gpu
a.to(device)

tensor([[0., 0., 0.],
        [0., 0., 0.]], device='cuda:0')

In [77]:
import time

In [78]:
size =10000


In [79]:
matrix_cpu1 = torch.rand(size,size)
matrix_cpu2 = torch.rand(size,size)

In [80]:
# measure the time pon cpu of matrix multiplication
start = time.time()
result = matrix_cpu1 @ matrix_cpu2
end = time.time()
print(end-start)

16.984851598739624


In [81]:
# moving matrices to gpu
matrix_gpu1 = matrix_cpu1.to(device)
matrix_gpu2 = matrix_cpu2.to(device)
start = time.time()
result = matrix_gpu1 @ matrix_gpu2
end = time.time()
print(end-start)

0.12081646919250488


### Reshaping Tensors

In [82]:
a = torch.ones(4,4)

In [83]:
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [84]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [85]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [86]:
b = torch.rand(2,3,4)
b

tensor([[[0.7855, 0.0214, 0.4146, 0.8320],
         [0.9449, 0.4601, 0.9553, 0.2526],
         [0.6500, 0.5545, 0.2594, 0.1109]],

        [[0.6692, 0.7747, 0.8302, 0.0576],
         [0.0599, 0.3868, 0.6465, 0.8070],
         [0.8066, 0.0374, 0.7435, 0.2796]]])

In [87]:
# permute
b.permute(2, 0, 1)
# re arranging the rows

tensor([[[0.7855, 0.9449, 0.6500],
         [0.6692, 0.0599, 0.8066]],

        [[0.0214, 0.4601, 0.5545],
         [0.7747, 0.3868, 0.0374]],

        [[0.4146, 0.9553, 0.2594],
         [0.8302, 0.6465, 0.7435]],

        [[0.8320, 0.2526, 0.1109],
         [0.0576, 0.8070, 0.2796]]])

In [112]:
# unsqueeze
c = torch.rand(226,226,3)

In [113]:
c.unsqueeze(dim=0).shape

torch.Size([1, 226, 226, 3])

In [114]:
c.unsqueeze(dim=1).shape

torch.Size([226, 1, 226, 3])

In [115]:
c=c.unsqueeze(dim=2)

In [116]:
# squeeze
c.shape

torch.Size([226, 226, 1, 3])

In [117]:
c=c.squeeze(dim=2)

In [118]:
c.shape

torch.Size([226, 226, 3])

### Numpy and pytorch

In [119]:
import numpy as np

In [120]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [121]:
b = a.numpy()

In [122]:
type(b)

numpy.ndarray