In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
! unzip /content/breast_cancer.zip

Archive:  /content/breast_cancer.zip
replace breast-cancer.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n


In [ ]:
df =pd.read_csv("/content/breast-cancer.csv")

In [ ]:
df.shape

(569, 32)

In [ ]:
df.head(n=3)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38           122.8     1001.0   
1    842517         M        20.57         17.77           132.9     1326.0   
2  84300903         M        19.69         21.25           130.0     1203.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33            184.6      2019.0   
1  ...         24.99          23.41            158.8      1956.0   
2  ...         23.57          25.53            152.5      1709.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  

[3 rows x 32 columns]

In [ ]:
df =df.drop(["id"], axis=1)

In [ ]:
df.shape

(569, 31)

In [ ]:
df.head(n=3)

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38           122.8     1001.0   
1         M        20.57         17.77           132.9     1326.0   
2         M        19.69         21.25           130.0     1203.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33            184.6   
1         0.1812  ...         24.99          23.41            158.8   
2         0.2069  ...         23.57          25.53            152.5   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  

[3 rows x 31 columns]

### Train Test Split

In [ ]:
X = df.drop("diagnosis", axis=1)
y = df["diagnosis"]

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# scaling
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
x_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [ ]:
y_train

68     B
181    M
63     B
248    B
60     B
      ..
71     B
106    B
270    B
435    M
102    B
Name: diagnosis, Length: 455, dtype: object

In [ ]:
y_test

204    B
70     M
131    M
431    B
540    B
      ..
486    B
75     M
249    B
238    B
265    M
Name: diagnosis, Length: 114, dtype: object

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,

In [ ]:
y_test

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1])

In [ ]:
# converting Numpy arrays to Pytorch tensors
x_train = torch.tensor(x_train, dtype=torch.float32)
x_test = torch.tensor(x_test, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32)
y_test = torch.tensor(y_test, dtype=torch.float32)

In [ ]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

(torch.Size([455, 30]),
 torch.Size([114, 30]),
 torch.Size([455]),
 torch.Size([114]))

In [ ]:
# Building a Neural Network


In [ ]:
class MySimpleNN():
  def __init__(self, x):
    self.weights = torch.rand(x.shape[1], 1, dtype=torch.float32, requires_grad=True)
    self.bias = torch.rand(1, dtype=torch.float32, requires_grad=True)

  def forward(self, x):
    z= torch.matmul(x, self.weights) + self.bias
    y_pred =torch.sigmoid(z)
    return y_pred

  def loss_cross_entropy(self, y_pred, y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
    loss = -(y_train * torch.log(y_pred) + (1 - y_train) * torch.log(1 - y_pred)).mean()
    return loss






### Important Parameters

In [ ]:
lr =0.1
epochs = 25

### training Pipeline

In [ ]:
# create model
model = MySimpleNN(x_train)

In [ ]:
#model.weights

In [ ]:
print(y_pred.shape)

torch.Size([455, 1])


In [ ]:
#y_pred

In [ ]:
type(y_pred)

torch.Tensor

In [ ]:
type(y_test)

torch.Tensor

In [ ]:
y_test

tensor([0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0.,
        0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
        0., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1.,
        0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1.,
        0., 0., 1., 0., 0., 1.])

In [ ]:
print(y_test.shape)

torch.Size([114])


In [ ]:
#y_train.unsqueeze(1)

In [ ]:
for epoch in range(epochs):
  # forward pass
  y_pred = model.forward(x_train)
  #print(y_pred)
  # loss caluclate
  loss = model.loss_cross_entropy(y_pred, y_train.unsqueeze(1))
  # backward pass
  loss.backward()
  # parameters update
  with torch.no_grad():#graient tracking off
    model.weights -= lr * model.weights.grad
    model.bias -= lr * model.bias.grad

  # zero gradients : to avoid accumulation of gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  print(f"Epoch: {epoch +1}, loss: {loss.item()}")

Epoch: 1, loss: 1.1568188667297363
Epoch: 2, loss: 1.0996344089508057
Epoch: 3, loss: 1.0531264543533325
Epoch: 4, loss: 1.0156930685043335
Epoch: 5, loss: 0.9856002330780029
Epoch: 6, loss: 0.9611784219741821
Epoch: 7, loss: 0.9409668445587158
Epoch: 8, loss: 0.9237947463989258
Epoch: 9, loss: 0.9087924361228943
Epoch: 10, loss: 0.8953520655632019
Epoch: 11, loss: 0.8830693960189819
Epoch: 12, loss: 0.8716832399368286
Epoch: 13, loss: 0.861027717590332
Epoch: 14, loss: 0.850996732711792
Epoch: 15, loss: 0.8415204882621765
Epoch: 16, loss: 0.8325512409210205
Epoch: 17, loss: 0.8240535855293274
Epoch: 18, loss: 0.8159998655319214
Epoch: 19, loss: 0.808366596698761
Epoch: 20, loss: 0.8011331558227539
Epoch: 21, loss: 0.7942802906036377
Epoch: 22, loss: 0.7877896428108215
Epoch: 23, loss: 0.7816441059112549
Epoch: 24, loss: 0.7758268117904663
Epoch: 25, loss: 0.7703216075897217


In [ ]:
# evaluation
with torch.no_grad():
  y_pred = model.forward(x_test)
print(y_pred)

tensor([[0.4453],
        [0.4113],
        [0.3974],
        [0.6769],
        [0.6888],
        [0.6338],
        [0.3751],
        [0.4310],
        [0.4710],
        [0.3530],
        [0.6047],
        [0.4788],
        [0.5974],
        [0.8079],
        [0.2889],
        [0.8308],
        [0.4600],
        [0.8508],
        [0.7298],
        [0.5836],
        [0.3564],
        [0.6737],
        [0.6891],
        [0.5946],
        [0.7247],
        [0.6845],
        [0.2738],
        [0.7200],
        [0.5946],
        [0.4566],
        [0.5633],
        [0.3785],
        [0.6946],
        [0.4094],
        [0.6532],
        [0.6214],
        [0.5679],
        [0.5096],
        [0.3823],
        [0.6371],
        [0.6281],
        [0.5789],
        [0.4437],
        [0.4421],
        [0.7632],
        [0.4945],
        [0.8730],
        [0.7988],
        [0.4548],
        [0.4159],
        [0.3197],
        [0.5035],
        [0.7231],
        [0.6610],
        [0.6177],
        [0

In [ ]:
# to calculate the accuracy we have to convert our y_pred to 0 and 1
y_pred = (y_pred > 0.5).float()

In [ ]:
y_pred

tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
      

In [ ]:
# accurcay
accuracy = (y_pred == y_test.unsqueeze(1)).float().mean()

In [ ]:
accuracy

tensor(0.4211)