In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [4]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [5]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [6]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [7]:
X_train

array([[-0.88888325, -0.86983671, -0.85652678, ..., -0.52205875,
        -0.53482455,  1.30389011],
       [ 0.33378985, -1.50804408,  0.26525362, ..., -0.16158902,
        -0.96822196, -0.51926898],
       [ 0.4674762 , -0.02203357,  0.62611453, ...,  1.50165219,
         2.22829149,  1.13944401],
       ...,
       [-0.21488122,  0.53139349, -0.25724712, ..., -0.87768996,
        -0.44183507, -0.96656237],
       [-0.84432113, -1.03233231, -0.84602019, ..., -0.70531769,
         0.49636238, -0.62177371],
       [ 1.26402405,  0.22053233,  1.23226388, ...,  0.52638803,
        -0.93335091, -0.54832112]])

In [ ]:
y_train

54     M
310    B
122    M
495    B
447    B
      ..
16     M
225    B
71     B
330    M
467    B
Name: diagnosis, Length: 455, dtype: object

In [8]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [9]:
y_train

array([0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,

In [23]:
X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [24]:
X_train_tensor.shape

torch.Size([455, 30])

In [25]:
y_train_tensor.shape

torch.Size([455])

In [26]:
from torch.utils.data import Dataset, DataLoader
class CustomDataset(Dataset):
  def __init__(self, X, y):
    self.X = X
    self.y = y
  def __len__(self):
    return len(self.X)
  def __getitem__(self, idx):
    return self.X[idx], self.y[idx]



In [27]:
# creating two different dataset object
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [28]:
# data loaders
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

In [29]:
train_dataset[10]

(tensor([ 1.1554, -0.1045,  1.0949,  1.0430,  0.0615,  0.1351,  0.2957,  0.7942,
         -0.0218, -0.8757, -0.0040, -1.2184, -0.1451,  0.1772, -0.7516, -0.4852,
         -0.2502, -0.0460, -0.9594, -0.4948,  1.1436, -0.1238,  0.9919,  1.0452,
          0.4417,  0.1368,  0.5212,  0.9588, -0.1512, -0.1224]),
 tensor(1))

In [17]:
train_loader

In [30]:
# defining the model
import torch.nn as nn
class MySimpleNN(nn.Module):
  def __init__(self, num_features):
    super(MySimpleNN, self).__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()
  def forward(self, features):
    out = self.linear(features)
    out = torch.sigmoid(out)
    return out

In [31]:
learning_rate = 0.1
epochs = 200

In [32]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

#define loss function
loss_function = nn.BCELoss()

In [33]:
# define loop
for epoch in range(epochs):

  for batch_features , batch_labels in train_loader:
    # forward pass
    y_pred = model.forward(batch_features)
    loss = loss_function(y_pred, batch_labels.unsqueeze(1).float())

    # backward pass
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    print(f'Epoch: {epoch} | Loss: {loss.item()}')

Epoch: 0 | Loss: 0.5259487628936768
Epoch: 0 | Loss: 0.4728309214115143
Epoch: 0 | Loss: 0.3573055565357208
Epoch: 0 | Loss: 0.35221073031425476
Epoch: 0 | Loss: 0.2955872714519501
Epoch: 0 | Loss: 0.33309951424598694
Epoch: 0 | Loss: 0.26111623644828796
Epoch: 0 | Loss: 0.25420689582824707
Epoch: 0 | Loss: 0.20456847548484802
Epoch: 0 | Loss: 0.2278125137090683
Epoch: 0 | Loss: 0.26039692759513855
Epoch: 0 | Loss: 0.20847240090370178
Epoch: 0 | Loss: 0.14789338409900665
Epoch: 0 | Loss: 0.26364317536354065
Epoch: 0 | Loss: 0.16650615632534027
Epoch: 1 | Loss: 0.15675029158592224
Epoch: 1 | Loss: 0.22936703264713287
Epoch: 1 | Loss: 0.14594393968582153
Epoch: 1 | Loss: 0.11086294800043106
Epoch: 1 | Loss: 0.23161651194095612
Epoch: 1 | Loss: 0.20932823419570923
Epoch: 1 | Loss: 0.14081642031669617
Epoch: 1 | Loss: 0.18749414384365082
Epoch: 1 | Loss: 0.2011720985174179
Epoch: 1 | Loss: 0.141198068857193
Epoch: 1 | Loss: 0.10373954474925995
Epoch: 1 | Loss: 0.1465795934200287
Epoch: 1 |

In [35]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.5369344353675842
