In [1]:
from sklearn.datasets import make_classification

In [2]:
import torch

In [3]:
X, y = make_classification(n_samples=1000,
                           n_features=20,
                           n_informative=15,
                           n_redundant=5,
                           random_state=1)

In [4]:
X.shape

(1000, 20)

In [5]:
y.shape

(1000,)

In [6]:
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.float32)

In [7]:
from torch.utils.data import Dataset, DataLoader

In [8]:
class customDataset(Dataset):
  def __init__(self, features , labels):
    self.features = features
    self.labels = labels
  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self,index):
    return self.features[index], self.labels[index]
    # we can apply any tranformation

In [9]:
dataset = customDataset(X,y) # dataset object

In [10]:
len(dataset)

1000

In [11]:
dataset[100]

(tensor([-5.3231, -5.7663,  0.8046,  1.2442, -1.0874, -2.9752, -4.7377,  0.6135,
          5.0712, 14.3700, -2.5531,  5.1197, -3.5467, -2.5585, -1.9521, 11.1268,
          9.5342, 10.0839,  0.4133, -5.1056]),
 tensor(1.))

In [12]:
dataloader = DataLoader(dataset, batch_size=100, shuffle=True)

In [13]:
for batch_features, batch_labels in dataloader:
  print(batch_features.shape, batch_labels.shape)
  print(batch_features)
  print(batch_labels)

torch.Size([100, 20]) torch.Size([100])
tensor([[-0.7996,  0.1576,  2.6659,  ...,  1.4995,  2.8083,  1.8536],
        [ 1.9627, -2.8767, -4.0830,  ...,  4.9540, -0.9625,  2.9120],
        [-1.6242, -4.2739,  0.4833,  ...,  2.6749, -1.0737, -4.0426],
        ...,
        [-0.7400, -0.6836, -4.1424,  ...,  1.6164,  0.5364, -0.8842],
        [-0.4389, -4.2913, -4.5724,  ...,  8.7542, -0.4355,  3.1959],
        [-3.9952,  0.5576,  2.2341,  ...,  1.4206, -2.1818,  1.6312]])
tensor([1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1.,
        0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0.,
        0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 1., 1., 0., 1.,
        0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
        0., 1., 1., 0., 0., 1., 1., 0., 1., 0.])
torch.Size([100, 20]) torch.Size([100])
tensor([[  0.3346,   2.5330,   0.3545