In [1]:
import torch

In [2]:
x = torch.tensor(3.0, requires_grad=True)
# it will provide the derivative by
#requires_grad=True

In [3]:
x

tensor(3., requires_grad=True)

In [4]:
y = x**2

In [5]:
y

tensor(9., grad_fn=<PowBackward0>)

#### grad_fn=<PowBackward0> means?
- It creates a computational graph x - sq-y: moves forward gives y = x**2
- If it moves backwards it gives y= 2x
- It means when moving backwards it provide the derivates


In [6]:
x

tensor(3., requires_grad=True)

In [7]:
y.backward()


In [8]:
x.grad

tensor(6.)

In [9]:
x = torch.tensor(2.0, requires_grad=True)

In [10]:
y = x**2

In [11]:
z = torch.sin(y)

In [12]:
y

tensor(4., grad_fn=<PowBackward0>)

In [13]:
z

tensor(-0.7568, grad_fn=<SinBackward0>)

In [14]:
z.backward()

In [15]:
x.grad

tensor(-2.6146)

In [16]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)

In [17]:
x

tensor(6.7000)

In [18]:
y

tensor(0.)

In [19]:
w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [20]:
w

tensor(1., requires_grad=True)

In [21]:
b

tensor(0., requires_grad=True)

In [22]:
z = w*x +b

In [23]:
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [24]:
y_pred = torch.sigmoid(z)

In [25]:
loss =torch.binary_cross_entropy_with_logits(y_pred, y)

In [26]:
loss

tensor(1.3124, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)

In [27]:
loss.backward()

In [28]:
print(w.grad)
print(b.grad)

tensor(0.0060)
tensor(0.0009)


In [29]:
x = torch.tensor([1.0,2.0,3.0], requires_grad=True)

In [30]:
x

tensor([1., 2., 3.], requires_grad=True)

In [31]:
y = (x**2).mean()
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [32]:
y.backward()

In [33]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

In [34]:
# clearing grad
x.grad.zero_()

tensor([0., 0., 0.])

In [35]:
# gradient tracking disabling
x = torch.tensor([1.0,2.0,3.0], requires_grad=True)
x

tensor([1., 2., 3.], requires_grad=True)

In [36]:
y = x**3
y

tensor([ 1.,  8., 27.], grad_fn=<PowBackward0>)

In [37]:
y = (x**3).mean()
y.backward()

In [38]:
x.grad

tensor([1., 4., 9.])

In [39]:
# 1. requires_grad_(False)
# 2. detach()
# 3. wrap in torch.no_grad()

In [40]:
x.requires_grad_(False)

tensor([1., 2., 3.])

In [41]:
y = x**2

In [42]:
y

tensor([1., 4., 9.])

In [ ]:
y.bac

In [43]:
x.grad

tensor([1., 4., 9.])

In [ ]:
### Detach - create a new tensor
z = x.detach()

In [ ]:
z # no graient tracking

tensor([1., 2., 3.])

In [ ]:
y = (x**2).mean()
y

tensor(4.6667)

In [ ]:
y1 = z**2
y1

tensor([1., 4., 9.])

In [ ]:
y.backward()


RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [ ]:
y1.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [ ]:
# torch np grad